package server.models;

import org.json.simple.JSONObject;
import java.util.ArrayList;

public class QuizQuestion {

    private int quizId;    // Declaring the variable quizId as an integer.
    private int questionId;    // Declaring the variable questionId as an integer.

    public QuizQuestion(int quizId, int questionId) {  //  The constructor for the model java class. Are auto generated by intelliJ. Importing the variable that were declared above.

        this.quizId = quizId;    // The constructor for the quizId variable.
        this.questionId = questionId;    // The constructor for the questionId variable.

    }

    public int getQuizId() {    // The getter for the quizID variable, auto generated by intelliJ.
        return quizId;
    }

    public void setQuizId(int quizId) {    // The setter for the quizID variable, auto generated by intelliJ.
        this.quizId = quizId;
    }

    public int getQuestionId() {    // The getter for the questionID variable, auto generated by intelliJ.
        return questionId;
    }

    public void setQuestionId(int questionId) {    // The setter for the questionID variable, auto generated by intelliJ.
        this.questionId = questionId;
    }

    public static ArrayList<QuizQuestion> quizquestions = new ArrayList<>();    // Declaring an ArrayList called quizQuestion

    public static int nextId() {
        int id = 0;
        for (QuizQuestion q: quizquestions) {
            if (q.getQuizId() > id) {
                id = q.getQuizId();
            }
        }
        return id + 1;

    }

    @SuppressWarnings("unchecked")
    public JSONObject toJSON() {
        JSONObject j = new JSONObject();
        j.put("quizId", getQuizId());
        j.put("questionId", getQuestionId());
        return j;

    }

}